module.exports = [

  {
    id: 1,
    name: "Manhattan",
    address: "503 Broadway",
    city: "New York",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Parmin Aujla",
    phone: "+1 (646) 123-1234",
    email: "paujla@instock.com",
  },
  {
    id: 2,
    name: "Washington",
    address: "33 Pearl Street SW",
    city: "Washington",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Greame Lyon",
    phone: "+1 (646) 123-1234",
    email: "glyon@instock.com",
  },
  {
    id: 3,
    name: "Jersey",
    address: "300 Main Street",
    city: "New Jersey",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Gary Wong",
    phone: "+1 (646) 123-1234",
    email: "gwong@instock.com",
  },
  {
    id: 4,
    name: "San Fran",
    address: "890 Brannnan Street",
    city: "San Francisco",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Parmin Aujla",
    phone: "+1 (646) 123-1234",
    email: "paujla@instock.com",
  },
  {
    id: 5,
    name: "Santa Monica",
    address: "520 Broadway",
    city: "Santa Monica",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Sharon Ng",
    phone: "+1 (646) 123-1234",
    email: "sng@instock.com",
  },
  {
    id: 6,
    name: "Seattle",
    address: "1201 Third Avenue",
    city: "Seattle",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Daniel Bachu",
    phone: "+1 (646) 123-1234",
    email: "dbachu@instock.com",
  },
  {
    id: 7,
    name: "Miami",
    address: "2650 NW 5th Avenue",
    city: "Miami",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Alana Thomas",
    phone: "+1 (646) 123-1234",
    email: "athomas@instock.com",
  },
  {
    id: 8,
    name: "Boston",
    address: "215 Essex Street",
    city: "Boston",
    country: "USA",
    position: "Warehouse Manager",
    manager: "Vanessa Mendoza",
    phone: "+1 (646) 123-1234",
    email: "vmendoza@instock.com",
  },
];
